=== Utils

There are numerous utilities in YAF that are designed to make test development easier.

==== Localization

The standard Spring localization mechanism #(!!ссылка)# and the main class that implements it - `L10nService` - are used to provide localization in YAF.
This service can use resources both with an explicitly specified locale and with a locale set in `TestExecutionContext` (accordingly, the localization may be test-dependent).

This mechanism is also automatically used in the templating engine.

==== Templates engine

For dynamic processing of strings (files), the framework has a templating mechanism (class `TemplateService`).
Two template engines are supported:

. https://github.com/spullara/mustache.java[Mustache] - used by default, for localization and elsewhere.
. https://velocity.apache.org/[Velocity] - additional implementation, used to generate the final test execution report.

==== Store

In YAF two types of additional storage are implemented:

. `FileStore` #(!!ссылка)# - a wrapper over the usual file storage.
For example, it is used to store downloaded versions of mobile apps.
. `YafDbRepository` #(!!ссылка)# - Spring boot repository on top of https://rocksdb.org/[RocksDB]  (key-value store).
Objects that are stored in this DB should be Serializable.
To use this store just @Autowire `YafDbRepository` and use provided methods.
Default DB name is `tmpdb`, you can change it in properties `yaf.tempdb.name=...`.

==== YAF utils

. YafReflectionUtils
. YafBeanUtils (be careful, some methods of this class are cached
. YafBy

===== User extended YAF utils

If a developer wants to create utilities that work as context-dependently as, for example, PageObjects #(!!ссылка на пейджи)#, he needs to inherit this utility classes from the `Utils` class and mark them with the corresponding `@Condition` annotation.

===== Misc utils

. Capabilities Utils
. Date Utils
. File Utils
. Properties Utils
. Safe Parse


