name: Build and Publish YAF

on:
  push:
    branches:
      - main
      - feature/initial

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.6.0-jdk17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set GRADLE_USER_HOME
        run: echo "GRADLE_USER_HOME=$GITHUB_WORKSPACE/.gradle" >> $GITHUB_ENV

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and Publish
        run: gradle publish -parallel
